### ISSUE TITLE
Time-evolution operators

### ISSUE THREAD

**Issue by acroy** [JuliaQuantum/QuDynamics.jl#29]
For some applications it is useful to get the time-evolution operator itself instead of the propagated state (see discussion in BBN-Q/QSimulator.jl#6). The question is how we should integrate this into the current framework?

**Comment by amitjamadagni** [comment]
@acroy I was thinking on these lines, one method is to have a similar interface like `QuPropagator` and `QuPropagatorState`, the former, say `QuPropagatorOp` for the constraints of the problem, (that is basically `QuPropagator` without the initial state), the latter, say `QuPropagatorOpState` which can take the similar parameters as `QuPropagatorState`. But in this case, we may have to pass a `QuEquation` type or generate a `QuEquation`, alternatively we could just have a iterator implementation on `AbstractQuMatrix` which has to be evolved, on similar lines of the just the iterator version of `QuPropagator`.

**Comment by acroy** [comment]
Something like that could work. Maybe we should rename `QuPropagator` to `QuTimeEvolution` and then use `QuPropagator<:AbstractQuMatrix` for the operator itself? In the simplest version the constructor of `QuPropagator` takes a QuMatrix (=Hamiltonian) and one float argument (=propagation time) and simply calculates `expm(-im*H*t)`. Then it would behave as any other QuMatrix.

**Comment by amitjamadagni** [comment]
Closing this as we have `QuStateEvolution` and `QuEvolutionOp` added. Though time dependency remains but I guess that is a different case.
