### ISSUE TITLE
QuTiP interface in QuDynamics

### ISSUE THREAD

**Issue by amitjamadagni** [JuliaQuantum/QuDynamics.jl#38]
[QuTiP](http://qutip.org/) is a python package which has a solver framework as QuDynamics. It would be nice if we could support methods like `mesolve`, `sesolve`, `mcsolve` of QuTiP with QuDynamics framework in the background. This was discussed as a part of the GSoC 2015 proposal (the idea as mentioned by Qi) and here are the details : 
https://github.com/JuliaQuantum/JuliaQuantum.github.io/issues/20.

**Comment by acroy** [comment]
Could you give some more details about the functions, i.e., purpose, arguments and return values?

**Comment by amitjamadagni** [comment]
I guess we could have something on the following lines, the purpose is to have a similar API as that of QuTiP supported by QuDynamics. Looking at the [API documentation](http://qutip.org/docs/3.1.0/apidoc/functions.html#module-qutip.mesolve) of `mesolve` which itself has the following parameters   

```
mesolve(H, rho0, tlist, c_ops, e_ops, args={}, options=None, progress_bar=None)
```

The aim is to support a function with similar parameters, we could have something on the lines of 

``` julia
function qutip_mesolve(H::QuBase.AbstractQuArray, rho0::QuBase.AbstractQuArray, tlist::Vector .......)

# the function should could call the `QuPropagator` as follows, with method being obtained from          # options
qprop = QuPropagator(H, c_ops, rho, tlist, method())

# this could be  further used to compute the expectation values if given by `e_ops` or just return the     # evolved state at every time step

for (t,psi) in qprop:
            # do machinery
end

end
```

These were the initial ideas I had which could be further refined !

**Comment by acroy** [comment]
We can certainly have functions along the lines your propose. We have to be careful with the arguments though. It seems that `H` in QuTiP can be several different things and we have to decide if/how we support them. Moreover, we can't have different return types depending on the content (value) of `e_ops`, as this would be type in stable. However, we can have two versions `mesolve(H, rho0, tlist, c_ops; keyw...)` and `mesolve(H, rho0, tlist, c_ops, e_ops; keyw...)`.

**Comment by amitjamadagni** [comment]
Ref #41
